### PR TITLE
Fix situation when integration object is not set

### PR DESCRIPTION
**Pull request by hluchas**
I got undefined method getKeys() many times.

### CODE REVIEW

**Comment by escopecz** [comment]
I did similar fix here: https://github.com/KonstantinCodes/mautic-recaptcha/pull/13

I guess this repo did not get updated. Could you merge the original repo master into this one instead?

**Comment by hluchas** [comment]
Cherry picked this commit https://github.com/KonstantinCodes/mautic-recaptcha/pull/13/commits

**Comment by escopecz** [comment]
Wow, this is old. @hluchas can we close this?

**Comment by hluchas** [comment]
I remember one bug which is not happening now. Closing ...

**Pull request merged**
